# Generated by Django 4.0.6 on 2022-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matfenix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=10, verbose_name='Pedido')),
                ('actividad', models.CharField(max_length=500, verbose_name='Actividad')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Material Fenix',
                'verbose_name_plural': 'Material Fenix',
                'db_table': 'fenix',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='matperseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=10, verbose_name='Pedido')),
                ('actividad', models.CharField(max_length=500, verbose_name='Actividad')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Material Perseo',
                'verbose_name_plural': 'Material Perseo',
                'db_table': 'perseo',
                'ordering': ['fecha'],
            },
        ),
    ]
