# Generated by Django 4.0.6 on 2022-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0002_matfenix_concatenacion_matperseo_concatenacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matperseo',
            name='acta',
            field=models.CharField(default=0, max_length=100, verbose_name='Acta'),
        ),
    ]
