# Generated by Django 4.0.6 on 2022-08-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0005_alter_matfenix_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='matfenix',
            name='enperseo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matperseo',
            name='enfenix',
            field=models.IntegerField(default=0),
        ),
    ]
