# Generated by Django 4.0.6 on 2022-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0007_faltanteperseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faltanteperseo',
            name='observacion',
            field=models.CharField(default='-', max_length=200, verbose_name='Observación'),
        ),
    ]
