# Generated by Django 4.0.6 on 2022-08-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0008_faltanteperseo_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='faltanteperseo',
            name='cantidad_fenix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Can Fenix'),
        ),
    ]
