# Generated by Django 4.0.6 on 2022-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0009_faltanteperseo_cantidad_fenix'),
    ]

    operations = [
        migrations.AddField(
            model_name='faltanteperseo',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Diferencia'),
        ),
    ]
