# Generated by Django 4.0.6 on 2022-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0010_faltanteperseo_diferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perseo', models.CharField(max_length=100, verbose_name='Nombre Perseo')),
                ('nombre_fenix', models.CharField(max_length=100, verbose_name='Nombre Fenix')),
            ],
            options={
                'verbose_name': 'guia',
                'verbose_name_plural': 'guias',
            },
        ),
    ]
