# Generated by Django 4.0.6 on 2022-08-31 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0012_acta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acta',
            new_name='NumeroActa',
        ),
        migrations.AlterModelOptions(
            name='numeroacta',
            options={'verbose_name': 'Acta actual', 'verbose_name_plural': 'Acta actual'},
        ),
    ]
