# Generated by Django 4.0.6 on 2022-11-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlmateriales', '0013_rename_acta_numeroacta_alter_numeroacta_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faltanteperseo',
            new_name='NovedadPerseoVsFenix',
        ),
    ]
